### ISSUE TITLE
Allow users to change username

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#1078]
> As a user I want to be known as <newname> so that I can align all my online presence name with my cool new artist/band name

In Zendesk we send this out as a warning:

> Hi <oldusername>,
> 
> You have requested a username change. Please understand some of the disadvantages of changing your username before changing.
> 
> - All the links to your sounds on the internet will be broken.
> - People might have credited you when they used your sound, this credit will now "point to nothing"...
> - As your old username becomes freed up: someone might start using your old username!
> 
> If you are OK with all of these things happening, please reply to this message with the new username you would like to use. Please only use alphanumerical characters. Then make sure that the username you chose is not already taken, you can do this by creating a URL with your new username:
> 
> https://www.freesound.org/people/YOURUSERNAMEHERE
> 
> If this URL tells you there is no such page, you have a good new username.
> 
> greetings,
> 
> Bram

Perhaps it would be easier to automate this. I'm currently getting around 2 requests per week. Doing the username change "by hand" also has the weird side effect that the caches aren't updated until 48-or-so-hours afterwards, so the username is changed, but all the sound displays still point to the old username.

In zendesk we send this out as a warning:

> Hi <old username>,
> 
> We just changed your username to <new username>
> 
> From now on, please log in with that new username.
> 
> It will take a while before all your sounds show up with your new username, give it 48 hours and check again...
> 
> greetings,
> 
> Bram

**Comment by ffont** [comment]
This is related to the recent changes introduced in https://github.com/MTG/freesound/pull/1059, in which we store old usernames in an `OldUsername` table so that we can redirect to the new sound URL when a user changes his username.

When working in this PR, we could also add an extra check in the account view before raising 404 when the username does not match any user, and try in the `OldUsername` table. In here:

https://github.com/MTG/freesound/blob/2b36a25f17720255ad6294e13e91b418b7e876ce/accounts/views.py#L796-L800
