### ISSUE TITLE
New "assign to me" buttons in moderation

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#1092]
> As a moderator I want to be able to easily assign all currently open tickets from a user even if they have already been assigned to other moderators

> As a moderator I want to be able to assign a moderation ticket from the ticket page even if it is already assigned to another moderator

Currently moderation tickets can be assigned in 2 ways:

- By clicking on the "Assign to me" link below the user avatar in the "Users with new sounds section" (https://freesound.org/tickets/moderation/). This will assign ALL sounds pending moderation by user X.
- By clicking on the "Assign to me" link below each sound in the tardy users or tardy moderators section (https://freesound.org/tickets/moderation/). This will assign a single sound.

These two methods are insufficient because once tickets have been assigned to a moderator, there is no easy way in which another moderator can re-assign them to himself. We can improve that situation by implementing 2 new "assign to me" buttons:

- Add "assign to me" link in the ticket page (e.g. https://freesound.org/tickets/e775c5f550264ec5b59f92d1b04c6f9d/), next to the "assigned to" field.
- Add "assign all user X sounds pending moderation to me" link in the "uploaded sounds pending moderation" page for user X (e.g. https://freesound.org/tickets/moderation/pending/TechnoScore/)

**Comment by philtgun** [comment]
For the first scenario (https://freesound.org/tickets/moderation/) the "Users with new sounds" section contains the _sounds that are pending moderation with no assignee_. For example, in case if there are 2 sounds that are new, but one is already assigned to mod, this page will show only the sound that is not assigned. 

If you click on "1 new sound" near user avatar, you will go to "uploaded sounds pending moderation" page (https://freesound.org/tickets/moderation/pending/xxxx) that contains _all pending sounds with or without assignee_ (2 in the example). Is it intentional? Because it is a bit confusing to see label that says "1 new sound" that goes to list of 2 sounds.

**Comment by philtgun** [comment]
Yes, two sections for pending sounds should clear the confusion. Also it would be useful to add the info about the moderator for the pending assigned sounds
