### ISSUE TITLE
Geotags map is not case insensitive when filtering by tags

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#1100]
Similarly to the browse tags page, geotags map can be filtered by tags like this: `https://freesound.org/browse/geotags/<tag1>/<tag2>...`. When browsing tags we do it in a case insensitive way, so that `https://freesound.org/browse/tags/fireworks/` returns the same as `https://freesound.org/browse/tags/Fireworks/`. However this is not the case for geotags page. We should make it work so that, for example, `https://freesound.org/browse/geotags/Granollers/` returns the same as `https://freesound.org/browse/geotags/granollers/`.

**Comment by philtgun** [comment]
Browsing by tags performs Solr request, while browsing geotags relies on databse query. Maybe we should use Solr for geotags search also?

**Comment by ffont** [comment]
Hmm that's interesting. In the API we use Solr for doing geotag related queries. However in the Geotags app I see we do all DB queries. I don't know if there is reason for that (any idea @andrebola @alastair) but I'm quite sure we discussed about it. Also I see in the tags browse case tag filters can be accumulated, but geotags only supports filtering by one tag. I think it would be good to mimic the same functionality and be able to do things like `https://freesound.org/browse/geotags/tag1/tag2/`. Maybe you could implement what this issue says by using a `__iexact` in the DB query and then open another ticket for the "multiple tags filter" feature. Regarding the DB/solr case let's see first if  @andrebola or @alastair have anything to say.

**Comment by alastair** [comment]
First up, I think that the fix for this issue should just fix this issue - that is, make case-insensitive tags work.

Second: db vs solr. From what I remember, we do tag search in solr because it was much faster than on the db. It's not clear to me that this exact usecase exists in the API. I can only see text search + is_geotagged filter (https://freesound.org/docs/api/resources_apiv2.html#text-search). Making a guess, I suspect @ffont wrote search in the API with solr (which makes sense), and then added is_geotagged as a filter. I'm not sure if there is common code for "geotag search" in the API which we can use here as well

Third: search by multiple tags. Let's add a new issue for it if we think that it's useful.
I had a dig into the deep history of freesound and found some of @bdejong's code!
 * https://github.com/MTG/freesound/commit/bbc5a9bad0ad970c997e055522d40860c704ea9f tag search using solr: June 2009
 * https://github.com/MTG/freesound/commit/4ed991e3ed7e62f46521b868d2d4b13f554fb3e6 geotag search: December 2009

it looks like the answer is probably something like "the db was easier to do geotag search with, and we're only searching for 1 tag anyway"

**Comment by ffont** [comment]
In the API all the interesting geotag queries that you can do (besides is_geotagged) just come "for free" as we index latitude and longitude in a way that Solr understands these are geo spatial coordinates. Therefore there is no code to see.

It makes sense that we did not do that search in solr because it was not needed as we only filter by one tag. Let's leave it as it is by now, just add the `__iexact` thing and open a ticket for the "filter by multiple tags" feature. Then as part of the work to be done in that ticket I'd say to compare performance filtering in the DB and in Solr.
