### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one OldUsername -- it returned 2!

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1220]
I guess we shouldn't be able to add the same user twice to OldUsername - we should at the very least have a unique index on this field: https://github.com/MTG/freesound/blob/1fbb618c6e4cccc1e820f8ecd510ab85ecde94fc/accounts/models.py#L468

https://logserver.mtg.upf.edu/sentry/freesound-web/issues/1138/

```
MultipleObjectsReturned: get() returned more than one OldUsername -- it returned 2!
(3 additional frame(s) were not displayed)
...
  File "utils/username.py", line 60, in inner
    new_user = get_user_or_404(kwargs['username'])
  File "utils/username.py", line 45, in get_user_or_404
    user = get_user_from_username_or_oldusername(username)
  File "utils/username.py", line 37, in get_user_from_username_or_oldusername
    user = OldUsername.objects.get(username__iexact=username).user

MultipleObjectsReturned: get() returned more than one OldUsername -- it returned 2!
```

**Comment by ffont** [comment]
I did some research, the problem is with case insensitiveness. Our code avoids having to `OldUsername` objects with the same case insensitive `.username` property, so this error should not occur. However, this is not enforced at the DB level and it could happen that we see the error due to `OldUsername` objects create before the case insensitiveness restriction. To fix this error I will:

 * Improve unit tests to properly check that we don't allow changing usernames to a "distinct-case" version of a previous username. This was already being tested but the test was wrong and in reality we were testing that username could not be changed due to max username change restrictions. By making sure this case insensitive restriction is in place, the error reported in this issue should not happen again.
 * Add `unique=True` to the `OldUsername.username` property. This does not enforce case insensitiveness, but apparently we can't set such restriction in Django unless we use some other 3rd party field type.
 * Remove existing instances of `OldUsername` objects with "distinct-case" versions of the same username

**Comment by ffont** [comment]
As an additional note, we can enforce case insensitiveness at the DB level for `OldUsername.username` property by adding custom SQL in a migration, similar to:
https://github.com/MTG/freesound/blob/fb09da014c3aa30b617ed8fd5dbe92961cb3f23e/accounts/migrations/0018_sameuser_case_insensitive_emails.py#L44
