### ISSUE TITLE
BUG - Server error when describing sounds with particular unicode text characters.

### ISSUE THREAD

**Issue by AxonFlux** [MTG/freesound#1254]
Whilst describing sounds in the upload portal, a user will be returned with a server error when trying to input unicode U+00E1 [á] in the tags field

The bug is reproducible, tested also with unicode U+00E2; same result, so the affected characters may be extensive. 

Please look into this. 
Cheers
Sam

**Comment by alastair** [comment]
This is a duplicate of #1230, so I'll close this one. It's on our roadmap to add support for some more characters (but we're not sure exactly how many yet).
Please add a :+1: to the original issue if you want to vote it! Thanks.

**Comment by alastair** [comment]
I'm reopening this because there are actually 2 things that we have to consider here:
 * The server error that happens if you add a non-ascii tag
 * supporting unicode tags

We should fix the server error even if we don't immediately support all unicode tags.. Opening this issue to track the first error.

**Comment by ffont** [comment]
I agree for now we should raise this as a validation error.
