### ISSUE TITLE
Add ability to group sounds by pack on user profiles

### ISSUE THREAD

**Issue by Headphaze** [MTG/freesound#1431]
New feature proposal for UI update...

Say for example someone wants to browse by profile if they like a particular uploader, It would be best to group sounds by pack on the user profile. This would make navigating users' sounds much easier if they have many pages of uploads. I think the fact that there are potentially many single entries on the list makes it daunting to browse this way. 

This would ideally be implemented with an option to switch it off whilst browsing the "sounds by X" page like we have in the advanced search function. Or off by default with an option to switch on. 

Any thoughts?

**Comment by ffont** [comment]
This is a nice suggestion. Main problem is that the way in which sounds are retrieved in the search page and in other pages (including user profiles) is fundamentally different. In user profiles we get it directly from database, in search engine we get it from our indexed search server. I think it would be nice to somehow unify the different ways to list sounds, that'd give us more options like grouping by pack or adding filtering facets easily.

There are several ways in which we could achieve this. The simplest one might be that the "more..." link in user profile page goes to a search page with a user filter applied. Then you could continue browsing there. It could be the case that new interface already plans to do it this way (not sure now). Another way to do it would be to make the code for the search page more modular and be able to "embed" search results in the user profile with an option to group by pack.

The main problem of relying on the search server instead of directly in database is that sometimes these are out of sync for some time (e.g. a sound is edited but changes are not reflected in the search page until X minutes have passed). But this could be improved easily. Also we could add some warning when we know there are sounds which should be reindexed, e.g. "there are X sounds from user X which have not yet been indexed". 

@alastair can you think of any reason why using the search page for browsing user uploaded sounds would not be a good idea?

**Comment by alastair** [comment]
I think using search for any kind of sound listing is a good idea if it allows us to do more interesting filtering and grouping 👍

**Comment by ffont** [comment]
Closing this issue as in the new UI you can do that
