### ISSUE TITLE
Registration email error message

### ISSUE THREAD

**Issue by Headphaze** [MTG/freesound#1514]
During registration if you enter an email address that is already associated with an account, you get a generic and erroneous message "You cannot use this email address to create an account."

This is misleading in the sense that some users trying to register forget they have an old account and when they try to register they end up opening a support ticket to complain that their email is valid. 

We need to be more specific with this message so that they know to send themselves a password reset request instead. e.g. "this email already belongs to an account" or "This email already exists, try sending a password reset" etc 

Cheers

**Comment by alastairporter** [comment]
This is a difficult balance to get right. The reason that we use such a generic message in this case is that we don't want to make it easy for people/spammers to verify that an email address is used in freesound. If we explicitly said "this email address is used in freesound" then we would make that information public.

We may be able to add some additional information ("this could be because there is already an account with this email address, or ...., or...."). I'll have a think about the best way to say it.

**Comment by Headphaze** [comment]
I understand. Makes sense now you've put it like that. I wonder why other websites are fine with stating this info though? That's what confuses me.
