### ISSUE TITLE
BW user profile page tries to continually load image if it doesn't exist

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1544]
For some reason the profile page has an onerror handler in the img tag

https://github.com/MTG/freesound/blob/5ff8393daa5bc6adb8068ab09802945fcabb6e9d/templates_bw/accounts/account.html#L18

This is a result that if the L image doesn't exist (issue happened in my dev environment because I don't have images), it'll try forever to load it - it was doing it so much that it caused chrome to use all my CPU and my computer fans to spin up.

We should instead update the locations method in python to create a "preferred avatar" url which is the XL if it exists or L if not.

**Comment by ffont** [comment]
Ups, sorry about that hehe.
In BW we have a new size XL, that is why I added this bad code. I think the better solution is to simply duplicate current .L.png  image files and rename to .XL.png so they exist in disk (oh, and remove that onerror handler). Then, whenever users update their avatars the files will be replaced with better quality ones.  In this way we don't add more checks for files existing in disk and the like. We could do that already as newly updated avatars in Freesund are already creating the XL version since last deploy. Does it make sense to you @alastair?

**Comment by ffont** [comment]
I removed the `onerror` handler and copied the files as described above. Closing this issue :)
