### ISSUE TITLE
API documentation confusingly doesn't include all query parameters in a single place

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1629]
I was reading the API documentation yesterday in order to test the API. I knew that there was a parameter to specify the return fields, but I couldn't see it in the "Request Parameters" section of the docs

<img width="837" alt="Screen Shot 2022-12-08 at 10 49 58 AM" src="https://user-images.githubusercontent.com/19217/206415369-b6d68a5e-6fe3-4043-b2d6-8a222d261db9.png">

I knew that the documentation was there, but it wasn't until I scrolled down further that I saw that some parameters are defined in the "Response" section of the docs:
<img width="848" alt="Screen Shot 2022-12-08 at 10 51 17 AM" src="https://user-images.githubusercontent.com/19217/206415597-532b41fe-e88e-4aff-9b73-9c16e00f5dea.png">

I wonder if this is part of the reason why people don't correctly use `fields` when performing searches - they look at the documentation and see the query parameters, but don't scroll down further to see the output parameters. I think that these tables should be moved together - they could still be separate - "These parameters are for querying", "these parameters are for controlling output", but it would then put all parameters in a single place to quickly see at a glance.

**Comment by ffont** [comment]
The reason why these two groups of parameters are separated is because the first set of parameters is only used for text queries while the other parameters are common to all end points that return a "list of sounds". I agree it can be confusing if the documentation is not read carefully. Maybe we should find a way to repeat parameter description without duplicating code, or do something like adding an extra row to the table that says "more parameters here" (with a link).
