### ISSUE TITLE
Option for quick citation text for attribution

### ISSUE THREAD

**Issue by Wilker-uwu** [MTG/freesound#1681]
Hi! First, thank you all for making this exist <3

second, i'd like to request an option to quickly copy into my clipboard or a file, a block of text containing basic attribution information about the author(s) of a piece as well as the license and link, regardless if the sound is Creative Commons or Public Domain. that would make it much easier to attribute whoever makes any sounds i happen to use in my projects.

again, thank you for your time <3

**Comment by ffont** [comment]
Hi @Wilker-uwu,
Thanks for this timely suggestion, I'll see if I can include now that I'm working in the new UI.

Cheers

**Comment by Wilker-uwu** [comment]
thank you <3

would also be nice to have a couple options for formatting (xml, json, latex, etc.) if that wasn't already considered :3

**Comment by Bomme** [comment]
We could take inspiration from attribution builders, such as:
https://www.deakin.edu.au/library/help/attribution-builder or https://www.openwa.org/attrib-builder/

**Comment by ffont** [comment]
Yeah, the big question for me is where to place the "button". Once clicking a button we can open a modal with options. Maybe something like that?

![Screenshot 2024-02-21 at 12 31 51](https://github.com/MTG/freesound/assets/478615/2134e796-a77d-4e71-a9dc-c07660dda551)

But it looks a bit ugly... ideas?

**Comment by ffont** [comment]
Thanks for the suggestions!
I think the button should be directly visible, specially if it opens a modal as otherwise it would be a lot of clicking. I thought about two more options:

* Have a "copy" button next to the License name (floating to the right)
* Add a fully fledged button above/below the "Download sound" button. The screenshot that I shared has the "Edit sound description" and "Edit in admin" buttons because I was logged in with my user and I have "superpowers", but non-admin users will only see the "Download sound" button, so it would be fine to add another button like "Get attribution text", which could be black button below the red download button (or grey button like the "Edit in the admin" of the screenshot).

What do you think?

**Comment by Wilker-uwu** [comment]
@ffont both ideas sounds good, i don't see why not keep both options. hovering over the license could immediately reveal a tooltip for copying the attribution at the current setting in one click (`Copy attribution {format}`/`Copied!`), and the main button reading "Attribute work" can show you a modal with all the details, one panel for format options and text area for copy, and the other gives you a brief description of the license with links to the full text. changing from there which format to copy from may or may not change the format copied when clicking the text from the main page, which can skip a step if someone's looking to use more than one audio.

**Comment by Bomme** [comment]
> could be in the expanded details of the license, either below showing up when expanding, or as a modal where both the license text and the text box are shown.

I have to say that I kind of agree with that! I think, that the license name should be a clickable link (instead of `More...` which is not very descriptive anyways) similar to the `xx downloads` and `xx comments`. 
Then `More...` could reveal the modal.

> Have a "copy" button next to the License name (floating to the right)

I think it's better to help people build the right attribution text (i.e. a modal with all the things) than a non descriptive buttons. As an extra it might work. 

> Add a fully fledged button above/below the "Download sound" button.

I think that would be nice too since it probably would be easier to spot. I would put it next to the license information though and not next to the download, so that the information is in one place.

**Comment by Wilker-uwu** [comment]
sounds good. that's two places to access the same modal and one of them to highlight a thing people can do :3

**Comment by ffont** [comment]
This has just been deployed!

**Comment by Wilker-uwu** [comment]
ayyyyyyyyyy
