### ISSUE TITLE
Player is not usable with stylus

### ISSUE THREAD

**Issue by ghost** [MTG/freesound#373]
Player pause button does not work when using a wacom stylus

**Comment by qubodup** [comment]
This ticket will most likely require much more information to be taken into consideration. Because you know, programmers and digital drawing equipment. :)

I cannot reproduce this error, bot the small and big players work with Wacom Bamboo using stylus on Arch Linux.

You might want to provide more information about your hardware and software (including os, wacom driver provider and wacom driver version) but the main thing is probably to test whether your expected behavior works on comparable sites like soundcloud and youtube and whether using the mouse works to get the result you want on the same machine to determine whether your hardware or software setup might be at fault.

**Comment by alastair** [comment]
check on mobile too, related to new interface.
