### ISSUE TITLE
Update pack select when describing multiple sounds and creating new packs

### ISSUE THREAD

**Issue by ghost** [MTG/freesound#635]
If you are describing more than one sound and don't want to add them all to a pack, you can edit the pack information on the last page of the describing process for each upload. But, if you want to add (for example) half of them to the same new pack, you need to insert a new pack name for the first sound. For each other uploaded sounds, you also have to fill in the "new pack" field, although the pack would be created after the first sound has been saved. A better way would be to update all pack - select boxes, if I have typed anything in a "new pack"-inputfield. 
Anyway, it worked. so no issue, but a feature request. :)

**Comment by ffont** [comment]
This is a bit tricky because I don't think it makes sense to display a pack in the dropdown list if it has not been created. Sure users will need to type the exact same pack name for all sounds that require it, but I don't think this is a problem (and there have been no complains about that). Closing the issue.
