### ISSUE TITLE
Uploads of large files seem to fail

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#668]
When uploading large files (say > 500mb) the upload process seems to fail.
We should reproduce the problem both using flash and non-flash uploader and work out what's going out. We should double check the maximum file upload size in the servers, which should be around 1GB.

frederic

**Comment by bdejong** [comment]
We should really be removing the flash-uploader to be honest... It's a bit of a shitty solution that's pretty old-school by now :(

Maybe there are some ready-made multi upload solutions out there? Some drag'n'drop power perhaps?

**Comment by bdejong** [comment]
This one seems to accept a lot of stuff:
https://blueimp.github.io/jQuery-File-Upload/index.html

**Comment by bdejong** [comment]
http://www.dropzonejs.com/ seems another one, no requirements outside of dropzone. I really like this part:

> Dropzone does not provide the server side implementation of handling the files, but the way files are uploaded is identical to simple file upload forms like this:
```
<form action="" method="post" enctype="multipart/form-data">
<input type="file" name="file" />
</form>

**Comment by alastair** [comment]
This looks like an nginx timeout issue, regarding how django processes uploaded files.

Django processes a form submission once it has received the entire request. With large files, we use a TemporaryFileUploadParser, and write to the freesound nfs share. https://github.com/django/django/blob/master/django/http/multipartparser.py#L127

I thought that this file was written to as the request comes in to django, but it looks like it's being buffered somewhere (gunicorn?), and gets given to django all at once. Django writes to the temporary file in chunks, and then calls our view code, which copies this file *again* using chunks, into the upload directory.

In our testing, a 700mb file takes about 25-30 seconds to copy from the buffer to the TemporaryFile. After 30 seconds, gunicorn times out and the request fails.

We temporarily solved this by increasing the gunicorn timeout to 60 seconds, however this affects all requests to FS, and should be moved back down if possible.

As we are now uploading temporary files to the same nfs drive as the uploads directory, an alternative to reading chunks would be to rename the file from the tmp directory to uploads, which should be really quick. This wouldn't work for in memory uploads though (<2.5mb). We could disable the in-memory upload handler to work around this.

For me, an ideal solution would be to write the file contents as the stream came in from the browser. I don't know if the buffering is happening at nginx, gunicorn, or django. It might require a separate upload service which we call from javascript, so that we can bypass django code.

**Comment by ffont** [comment]
Closing this ticket as we deployed new uploader and it seems to work ok now.

**Comment by ffont** [comment]
After chat with Alastair we decided it is better tor reopen the ticket and do further testing at some point.

**Comment by ffont** [comment]
Good that we re-opened this ticket 3 years ago because some problems still seem to exist. I could test with long files and sometimes these are uploaded correctly and copied to my fs user folder (so I can later describe) and sometimes this process files. Need to dig into that again at some point but this "randomness" could be related to the speed at which uploaded file is moved from tmp location to user folder.

**Comment by alastair** [comment]
From what we discovered, I believe that the easiest way to make the copy process take half as long is to do a move instead of a second copy, as I suggested in the previous comment.

Perhaps we could look at a new upload system with the new interface that doesn't suffer from this problem?

**Comment by ffont** [comment]
Sure, that makes total sense. I'll add the issue to the current project so it does not get lost.

**Comment by ffont** [comment]
Closing this issue as in recent commit I implemented moving tmp uploads instead of copying them: https://github.com/MTG/freesound/commit/d21959087d787a912cf9ea4b2ebaabeeead718e4

If this does not fix the issue, we can reopen in the future.

**Comment by ffont** [comment]
We're still seeing issues after deploying changes mentioned in previous commit, therefore I'm-reopening this issues.
The errors seem to happen for large files, only when the upload progress shown in web UI is at 100% and stays like that for a couple of minutes until we see "something went wrong" in red. I could asses that we're never reaching [this like in code](https://github.com/MTG/freesound/blob/d21959087d787a912cf9ea4b2ebaabeeead718e4/accounts/views.py#L1195) because this is not logged. But the uploads directory for the user (happening [two lines above](https://github.com/MTG/freesound/blob/d21959087d787a912cf9ea4b2ebaabeeead718e4/accounts/views.py#L1193)) seems to be run without problems...

**Comment by ffont** [comment]
After another quick test, it seems the errors now happen with sounds with non-ascii characters in them... This was probably already happening before the latest fixes. This is the line that is failing probably: https://github.com/MTG/freesound/blob/d21959087d787a912cf9ea4b2ebaabeeead718e4/accounts/views.py#L1194 (maybe silently failing because otherwise we would be notified I assume). We should further investigate this issue here and find a proper fix...
