### ISSUE TITLE
Optimise forum latest posts

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#674]
The query to get forum latest posts is quite slow. Could be probably optimised using custom SQL.

**Comment by andrebola** [comment]
Forum has a reference to the last_post, but the method get_last_post doesn't use it:
https://github.com/MTG/freesound/blob/c8ecaf2c36d3db4784c0242f2e0051a48d451dcf/forum/models.py#L67-L68

@ffont Is this what you refer? Or there is a specific part that it's slow?

**Comment by ffont** [comment]
For what I see in the code you're right that `get_last_post` could simply use the stored one. I guess this method was implemented before `last_post` was stored in the model. Maybe this method could be refactored so that if `last_post` is null, then `Thread.set_last_post()` is called before returning `self.last_post`. In this way we'll avoid extra queries.

**Comment by alastair** [comment]
I'm not sure I like the solution to this in 38f6336
* Because we do the potential lookup in a function, we can't add `last_post` to the forum with `select_related`. This means that we're always doing 1 extra db lookup for each forum that we have
* All of our forums already have a `last_post` set. What's the case when it might be null? When we have a new forum - in this case we don't have a post anyway, so `set_last_post` won't have any affect anyway
* In the template we check against `if forum.last_post.id` but then use `get_last_post` when printing the username and time of the post. This could be simplified to just use `last_post`
* `set_last_post` has some commented code which isn't used, and some badly formatted text layout. Since we're working on this code we could clean it up

I think we should remove `get_last_post` and make sure that when we select forums we do `select_related`. Can we override the forum manager to always do this for us?

**Comment by alastair** [comment]
Looking at the title of this issue again I wonder if it's actually talking about http://freesound.org/forum/latest_posts/ (which is already pretty fast, I don't think there's any further optimisation we need to do here)
