### ISSUE TITLE
Reindex sounds on pack edit

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#678]
When packs are edited (ie pack name changed), sounds should be set to index state dirty so that changes in the pack names are reflected in solr.

**Comment by ffont** [comment]
I used an update() query to set all sounds from the pack as index dirty, however that query can become too slow for packs with large number of sounds. We should change that in the future. Ideas are:
- Mark sounds as index dirty asynchronously 
- Create a job for indexing sounds (and potentially also for other tasks) that sits in the appserver and add sounds to the queue on pack edit
- Change the way in which sounds are selected for being reindexed in solr (eg: not only reindex sounds with is_index_dirty but also sounds from packs that were modified since last index)

**Comment by bdejong** [comment]
What about: have a separate server reindex sounds, send the ID's of things that need to be reindexed over a queue. There are so many things that should trigger re-indexing that are currently NOT being triggered...
For example: new comments don't sent sounds to dirty I think, but when you search comments are still in there (IIRC!)...

**Comment by alastair** [comment]
A new reindex server would work, but it's one more moving piece that I'm not sure we need. Since our gearman workers have access to postgres we could do it there. A few thoughts:

 - Don't do it asynchronously (in a thread, I mean - perhaps we could have another endpoint on gearman??)
 - If we are happy with indexes being out of date for less than an hour, we should keep using is_index_dirty
 - Why is it really slow to mark all sounds in a pack? How many songs are in this pack? This should just be a "simple" update statement. If it's slow then perhaps we need custom sql.
 - Is there a better way to set the index flag? Perhaps we could do it on a save hook (unless it's already being done like this - maybe we just need to update the list of fields we check)

**Comment by ffont** [comment]
I was thinking of a gearman job too but maybe is too much. The problem comes with packs that have large number of sounds, say hundreds. I did not think of custom sql because I looked at the update sql generated by django and it seemed ok, but maybe there was something else slowing the query. I observed a 4 second query for updating 600 records, should be faster right? I'll further look into that.

The orher option I was proposing is to improve post_dirty_sounds to solr by also considering sounds from packs edited since the last index (last hour). Should work too.

Regarding marking index dirty on commenting sounds should not be a problem, its only updating one sound.


El 22/07/2015, a les 16:37, Alastair Porter <notifications@github.com> va escriure:

**Comment by ffont** [comment]
We will implement that having a kind of sounds_are_index_dirty property in the pack model, and then make sure the post_dirty_sounds_to_solr also takes into account sounds under these packs

**Comment by ffont** [comment]
We were discussing this issue with alastair and thought that best way would
probably be to have a "is_index_dirty" property on the pack model too, and
also index sounds from packs that are index dirty at indexing time.

2015-07-22 17:16 GMT+02:00 Frederic Font <frederic.font@upf.edu>:
