### ISSUE TITLE
Individual Contributor License Agreement

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#697]
For other MTG projects such as Essentia and Gaia we have an Individual Contributor License Agreement, however, for freesound we don't. It would be good to have this so the full copyright can stay with MTG.

Here's the Essentia example:
http://essentia.upf.edu/sites/default/files/CLA.pdf

**Comment by alastair** [comment]
I don't think this is needed. Copyright should not stay with the MTG, it should belong to the person who makes contributions.

**Comment by bdejong** [comment]
I would check with Xavier Serra to be honest. Essentia is also GPL, also developed by MTG, but they do have a contributor license...

**Comment by alastair** [comment]
The GPL does not require that the original contributor retains copyright. Essentia has some special cases because MTG wishes to keep the option of commercially licensing it, for which it has decided to do by using the CLA. Note that the CLA doesn't actually assign copyright, it just gives MTG the option of being able to relicense essentia.
I don't think that we have a similar requirement in Freesound, and therefore there is no requirement to have additional agreements.

**Comment by xserra** [comment]
I would favor to have a CLA for external contributions to the freesound code. We now do not have any plan for commercially licensing the software, but I would not like to close that option. Precisely in the context of AudioCommons we will be exploring exploitation opportunities of Freesound and we should have as many options open as possible.

…xavier

---
Xavier Serra
Music Technology Group
Universitat Pompeu Fabra, Barcelona
http://www.dtic.upf.edu/~xserra/

**Comment by alastair** [comment]
After discussion offline we decided that this wasn't needed.
