### ISSUE TITLE
Sound.set_audio_info_fields(...) seems to fail if bitrate is not integer

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#722]
Logs from the processing server return the following error message when processing sound id=340857 

DatabaseError: column "none" does not exist
LINE 1: ...ate = 8000.0, bitrate = 31.7082143545, bitdepth = None, chan...

The problem seems to be related with the bitrate not being integer, but it is not clear as the bitrate computation does not seem to yield an integer result for other sounds that get processed ok.
Quick fix could probably be rounding the result of the bitrate computation, but it needs further investigation.

**Comment by andrebola** [comment]
For this sound the method `stereofy_and_find_info` returns:

`{'channels': 1.0, 'bitdepth': None, 'samplerate': 8000.0, 'bitrate': 31.708214354536377, 'duration': 39.9581}
`

While if I use the command `mediainfo` I get this output:
```

General
Complete name                            : /.../
Format                                   : Wave
File size                                : 158 KiB
Duration                                 : 40s 21ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 32.4 Kbps

Audio
Format                                   : ADPCM
Codec ID                                 : 11
Codec ID/Hint                            : Intel
Duration                                 : 40s 21ms
Bit rate mode                            : Constant
Bit rate                                 : 32.4 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 8 000 Hz
Bit depth                                : 4 bits
Stream size                              : 158 KiB (100%)

```

If I round the bitrate to integer then I get the following error:

```
{'channels': 1.0, 'bitdepth': None, 'samplerate': 8000.0, 'bitrate': 32, 'duration': 39.9581}
got sound info and stereofied: /tmp/396773MZUIJo.wav
Failed to process sound with id 396773
        message: failed writting audio info fields to db
        error: column "none" does not exist
LINE 1: ...SET samplerate = 8000.0, bitrate = 32, bitdepth = None, chan...

```

This is because stereofy doesn't return a bitdeph value, if you see the output of `mediainfo` the bitdeph is 4 bits which is not in the list: 
https://github.com/MTG/freesound/blob/4e4b91fa45adabb5294487eeed384596425fd8bb/_sandbox/stereofy/main.cpp#L18-L39

The question is if we want to add this bitdeph of if we should show a message saying that the file format is not supported?

**Comment by ffont** [comment]
I think we can simply handle the case where `"bitdepth": None` in `stereofy_and_find_info` and set it to 0 instead. In any case, this happens 0.0001% of times :)

**Comment by bdejong** [comment]
Adpcm we really shouldn't support. It's a terribly crappy Wav compression.
That said it's weird that it got through the rest of the process...
Libsndfile *might* support adpcm.

**Comment by ffont** [comment]
I think it is ok to set the bitdepth to 0 as @andrebola implemented in https://github.com/MTG/freesound/pull/949. Merging the PR.
