### ISSUE TITLE
Forum posts are never re-indexed

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#753]
Forum index in solr should behave in the same way as sound's index.
Posts should be able to be marked as index dirty, which should trigger update of the index asynchronously.
Also, when a post is deleted it should also be removed from the solr index.

**Comment by andrebola** [comment]
I stared doing this change and then I realized that there might be another way, instead we could just reindex all the posts every time since they are not many (52657 posts). 

In the Test server took around 30 seconds to index all the posts (after removing the line: https://github.com/MTG/freesound/blob/67615eaf5d30c58e7c6ef555d4f57208c582f14e/utils/search/search_forum.py#L49). I think we could run this process once every hour.

Now the code for add/delete documents has auto commit, so in this 30 seconds the users would not see any results, but if the code for reindexing the posts makes the commit after finishing the insert then this shouldn't happen.

@alastair, @bdejong do you see any problem with this.

**Comment by ffont** [comment]
The logger line can be deleted, also in `convert_to_solr_document` for sound objects (if it's there).
Can you check what happens with indexing/committing etc?

Maybe we don't need the full 'mark_index_dirty' thing, but we should probably have a delete function  and an edit function that we can call when forum posts are deleted or edited (so do it synchronously).
Then we can reindex the whole thing once a day for example to make sure we don't get out of sync
