### ISSUE TITLE
Report to users when they have duplicate accounts

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#761]
For email-login we want unique email addresses for all users.

Instead of automatically merging accounts, we have decided to ask users what to do, because they may have specific reasons to have separate accounts.

We need a new table, `SameAccounts`, which links accounts which share an email address.
Columns:
- core user id (account logged into most recently)
- other account id
- other account orig email

Change the email address of the account with the earliest `last_login` time from `email@provider.com` to `email%provider.com@freesound.org`, then we can finish the email login functionality, with a unique index on the email column.

When a user logs in, check if any of their accounts are in this table. If so, redirect them directly to a page explaining that they have multiple accounts and list the accounts. Put a check on Home as well, showing a banner which links to this page.

Tell them that they have three options:
1. Change the email address of their accounts
2. Merge them
3. Delete them
- If they log in to the account with the changed email address, tell them that they can change it -> send to the change form.
- If they log in to the account with the original email address, tell them to log in as the other one (give the username). If they don't know the password, tell them to contact support and provide a link with a message already filled in

If they want to merge or delete the accounts, tell them to contact support and provide a link with a message filled in.

When a user changes their email address, we need to remove them from the `SameAccounts` table if they were there

**Comment by ffont** [comment]
If many users ask us to delete or merge accounts, this might be some extra work for us. I agree with all said but I'd try at least not to present change email/delete/merge as options at the same level. In general I'd tell users they have to change the email and that's it.
Then I'd say something like "If you want to get rid of one of the accounts or merge them, please contact us at ...".
Well maybe this comment looks obvious but just wanted to make that point.

**Comment by bdejong** [comment]
I would say: let us give ONLY people the option to change or delete, not merge.

**Comment by alastair** [comment]
90% of the accounts in this situation only have downloads on one of the accounts. Merging them is easy.

There are ~30 accounts with many uploaded sounds + tickets + comments + messages, etc. If we have to merge only one of these (which we already have to do, from our previous emails to users), then we have to write the code, therefore we will have code for the general merge case as well.

To me, the change email case only makes sense for people who have two distinct accounts and actively participate using both of them. I think that delete and merge will be the most useful actions.

**Comment by qubodup** [comment]
GMail specific information:

martha@gmail.com will receive emails sent to martha+freesound@gmail.com

This is described on https://support.google.com/mail/answer/12096?hl=en

Assuming the amount of gmail re-use is critical, it would seem feasible to automatically change additional accounts to use martha+freesound1@gmail.com, martha+freesound2@gmail.com...  (of course you'd have to check each time the users didn't already manually create another account with that address in the past)

I just tested on my account: martha+test999999999999999999999999999999999999999999999999999999999999999999999999999999@gmail.com is still acceptable length.

I then recommend you write one email to the main address with a list of changes performed rather than emailing each of the newly generated ones, otherwise you'll surely land in spam.

**Comment by ffont** [comment]
Related to https://github.com/MTG/freesound/pull/763/
We simplified this process and only warn users whose email was automatically changed toa void duplicates. See PR for more information.
