### ISSUE TITLE
Renaming packs does not clear the old SOLR index

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#779]
http://freesound.org/search/?q=cuba+havana

see the first two packs mentioned (next to the ➕  sign): same username, same pack name, one is real the other isn't.

**Comment by bdejong** [comment]
This is the correct pack:
http://freesound.org/people/kyles/packs/20401/

This is rather weird:
http://freesound.org/people/kyles/packs/3339/
exists, but contains no sounds (wuh?)

Could this mean there is there no unique(user_id, pack.name) index in the db?

**Comment by andrebola** [comment]
I think the second pack was deleted but it wasn't updated on Solr. So, we should set index_dirty=True when the pack is deleted at line:

https://github.com/MTG/freesound/blob/7f64cdf864eee0f8af9d461232e72a9fb4ab5780/sounds/models.py#L838

**Comment by ffont** [comment]
Well, I don't think the pack was deleted because the object is there, but apparently the sounds were moved from the old pack (3339) to the new one (20401, probably using pack edit feature (https://github.com/MTG/freesound/blob/master/sounds/views.py#L435). What might be happening is that once a pack is edited, the sounds assigned to the pack are set to reindex, but the ones that were removed from the pack don't seem to be set to reindex. We should set all affected sounds to reindex and I guess this will fix the problem.

**Comment by andrebola** [comment]
I don't think that is the problem since the old and new sounds are marked as dirty on the save method of the form:

https://github.com/MTG/freesound/blob/master/sounds/forms.py#L177

So I don't see why the new sounds are marked in the view as well: https://github.com/MTG/freesound/blob/master/sounds/views.py#L465

**Comment by ffont** [comment]
According to @andrebola comment we don't think this issue is still valid.  However, we seem to be doing the mark index dirty two times, at pack edit view and at pack form save.

**Comment by andrebola** [comment]
I check the code again and some of the sounds might be marked as dirty two times but there are others sound related to the pack that will be marked dirty only once (in the edit view method).

**Comment by andrebola** [comment]
I just tested this in my local and it worked fine. Changing pack name sets is_index_dirty as True and then the management command post_dirty_sounds_to_solr indexed the sound.

**Comment by andrebola** [comment]
This issue is very related with #989. After merged the PR #1002 this could also be fixed by running the full index periodically.

**Comment by andrebola** [comment]
I think this problem was a mix of old data indexed in solr and packs that were deleted which was not reflected in solr. So I think the fix related to the full reindex and not indexing the deleted packs will solve this issue.
