### ISSUE TITLE
HTML escaping in emails

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#781]
A bug that has always existed in Freesound is that content is not unescaped properly in emails.

So, I regularly get emails like this:

```
Hello there admin,
A sound was flagged:
<snip>
Reason:
It&#39;s strongly doubted by two users ....<snip>
kindest,
- The Freesound Mail Robot!
```

The same happens with the comments:

I posted a comment on my own sound: http://freesound.org/people/Bram/sounds/210096/#comments

And got this email:

```
The user 'Bram' posted the following comment about VN650221.WAV:
speciâl character&#39;s test&quot; çava?
```

it seems to happen mostly with single and double quotes, but might happen with other characters too...

**Comment by alastair** [comment]
Are these emails sent as plain text, HTML, or both? It looks like plain text from here.

The characters which are escaped are HTML escape codes - it looks like this is because we're using django's `render_to_string` template function, which of course is used for HTML output. This causes problems when we send plain text emails. The "easy" solution would be to send html emails instead, in which case the text would render properly. Otherwise there may be a setting we can alter in the django templates system to not to html escaping for our email templates.

**Comment by alastair** [comment]
With plain text emails we should be able to fix this by using the `|safe` templatetag in the relevant email templates.
However, we have to be very careful here if we want to send hybrid text/html emails, where we escape the text in the html version but not in the text version.

**Comment by bdejong** [comment]
I don't care if the emails are HTML or Text. Actually, all emails we currently have are supposed to be text emails.
