### ISSUE TITLE
Think of ways to promote donations

### ISSUE THREAD

**Issue by andrebola** [MTG/freesound#785]
There are some ways to promote donations like Wikipedia does asking the users to contribute. For example, we could send an email to the users with more downloads in a period of time asking them to consider donating.

Also, checking the donations page, I see that there are some big donations from companies that are "lost" among small donations. I guess they would like to have more presence and appear as big sponsors, this could encourage them to make bigger donations.

I want to open this discussion to know if there is a way of promoting the donations without making it painful for the users.

**Comment by andrebola** [comment]
Sending mails to past donors is a good way of getting new donations. [source ](http://www.mrss.com/lab/benchmarks-bonus-email-rates-by-segment/)

**Comment by ffont** [comment]
This article is very interesting, thanks for sharing!

I'd say that overall this is good but I'd first work on other stuff like the badges.
Also we'll have to balance well the send email thing. In some cases we could show a popover for example (instead of sending email). I just linked existing donation objects with fs users (by email), so we'll have that information if we ever want to send some message to users that have donated.

Also I'm not sure how to deal with small vs big donations thing. To me all donations are good, even if they're small. I agree if there is an exceptionally high donation we can somehow make it more visible but I don't know how. And we haven't had such donations as far as I remember.

Anyway, lets come back to that in a few "issues" time :)

**Comment by alastair** [comment]
We've thought about this and even implemented something!
