### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='www.paypal.com', port=443): Max retries exceeded with url: /cgi-bin/web...

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#842]
A failure during paypal stuff is probably bad - we want to make sure that this happens as little as possible.

You can do retries in requests: http://stackoverflow.com/questions/15431044/can-i-set-max-retries-for-requests-request
Is this operation something that has to be done in the user workflow (e.g., we have to show something to the user afterwards?) or can we do it in a worker process and retry until it succeeds?

https://logserver.mtg.upf.edu/sentry/freesound-web/issues/624/

```
ConnectionError: HTTPSConnectionPool(host='www.paypal.com', port=443): Max retries exceeded with url: /cgi-bin/webscr (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x6b91650>: Failed to establish a new connection: [Errno -2] Name or service not known',))
(4 additional frame(s) were not displayed)
...
  File "donations/views.py", line 25, in donation_complete
    req = requests.post(settings.PAYPAL_VALIDATION_URL, data=params)

ConnectionError: HTTPSConnectionPool(host='www.paypal.com', port=443): Max retries exceeded with url: /cgi-bin/webscr (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x6b91650>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by andrebola** [comment]
When someone makes a donation we receive a notification from paypal, then we verify that the information we received with paypal's server ( in this last step occurs this error) and if the verification is fine we save the donation and notify the user.

The notification of the donation from paypal is sent many times for the same donation, in this case the donations has been validated and saved one minute later:
https://www.freesound.org/donations/donors/

I think for some reason paypal didn't respond to our request, this could be fixed by setting a number of retries but I'm not sure if this is required since paypal sends the same notification many times.

**Comment by alastair** [comment]
OK, to clarify: This URL is accessed by paypal, and then we get the body and send a confirmation to them to say that we have it. If we don't confirm, they see it again?

So this error won't be seen by an end user.

What is paypal's policy on retrying? Will they retry if we send anything other than HTTP 200? Only retry if we send 5xx? 

I think it would be good that we do at least the following
 * Use a session in requests to set `max_retries` for the POST,
 * Catch any `requests` errors and return our own custom http500 error instead of django's default crash handler if we can't make the POST (even after retrying)

**Comment by andrebola** [comment]
Paypal doesn't expect a confirmation, this a check we do to make sure that the information sent by paypal is right (and to validate it's paypal that send us this data). The other thing is that they call this a number of times, no matter if we fail to verify or not.

It's right, users won't see this error.
