### ISSUE TITLE
Can't reset password with email address

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#876]
Most of our account recovery pages let you enter a username or email address, but reset password only lets you enter a username. Expand to allow an email address too.

**Comment by andrebola** [comment]
I don't understand since the form validates the emails, like this:
https://github.com/MTG/freesound/blob/878a435a1e0a7921e6dd523c3dc09192ce8fed6a/accounts/tests.py#L849:L850

And the UI is also restricted to emails:

<img width="760" alt="captura de pantalla 2017-06-26 a la s 12 34 59" src="https://user-images.githubusercontent.com/991305/27547318-f77c5942-5a6b-11e7-9a59-64c743dd658e.png">
